package com.progetto.utils;

public class Constants {

	public static final String URLPROPERTIES = "C:\\Users\\alaera\\Desktop\\SpringFile\\ParamExternal.properties";
	public static final String PASSWORD_ENCRYPT = "password_encrypt";
	public static final String REGEX_PASSWORD = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$";
	public static final String ERROR_PASSWORD_MESSAGE = "la password deve contenere almeno 8 caratteri, almeno una lettera, almeno un numero e almeno un carattere speciale tra @, $, !, %, *, #, ? e &.";
	public static final String REGEX_EMAIL = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
	public static final String FORMAT_EMAIL_ERROR = "EMAIL FORMAT ARE INVALID, EXEMPLE OF A CORRECT EMAIL FORMAT: <namesurname>@<domain>.com";
	public static final String NAME_NOT_BLANK = "NAME CAN'T BE NULL OR EMPTY";
	public static final String INVALID_PAN_CODE = "PAN CODE NEED TO HAVE ONLY 10 DIGITS. EXEMPLE OF A PAN CODE: 1234567890";
	public static final String PAN_CODD_REGEX = "^\\d{10}$";
	public static final String IBAN_REGEX = "^IT\\d{2}[A-Z]\\d{10}[0-9A-Z]{12}$";
	public static final String INVALID_IBAN = "IBAN INSERT ARE INVALID, IBAN STARTS WITH IT, FOLLOWED BY TWO UPPERCASE ALPHABETIC CHARACTERS, FOLLOWED BY 10 DIGITS AND FINALLY 12 ALPHANUMERICAL CHARACTERS (UPPERCASE LETTERS AND DIGITS) IN ANY ORDER";
	public static final String SURNAME_NOT_BLANK = "SURNAME CAN'T BE NULL OR EMPTY";
	public static final String DATE_NOT_BLANK = "DATE CAN'T BE NULL";
	public static final String DATE_NOT_VALID = "DATE OF BORN ARE NOT VALID, YOU MUST BE OLDER THEN 18 YEARS OLD";
	public static final String PATTERN_DATE = "dd/MM/yyyy";
	public static final String EMAIL = "EMAIL: ";
	public static final String ERROR_SAVE_EMAIL_UNIQUE = "EMAIL ALREADY PRESENT IN THE SYSTEM: ";
	public static final String ERROR_CREDENTIAL = "USERNAME FORMAT ERROR, USE YOUR EMAIL OR IF YOUR ARE ADMIN YOUR ADMIN CODE";
	public static final String SAVE_DONE = "OPERATION DONE CORRECTLY";
	public static final String CLIENT_FOUND = "CLIENT FOUND CORRECTLY: ";
	public static final String CLIENT_NOT_FOUND = "CLIENT NOT FOUND";
	public static final String ERROR_GET_ALL = "NO USER PRESENT IN THE SYSTEM";
	public static final String GET_ALL_DONE = "PRINT ALL USERS PRESENT IN THE SYSTEM";
	public static final String DELETE_DONE = "CLIENT CORRECTLY DELETED FROM DATABASE";
	public static final String ERROR_GENERIC_SAVE = "ERROR DURING SAVE METHOD";
	public static final String COUNTRY_CODE = "conutryCode";
	public static final String CONTROL_DIGIT = "controlDigit";
	public static final String BANK_CODE = "bankCode";
	public static final String CAB = "cab";
	public static final String NATIONAL_CODE = "nationalCode";
	public static final String CURRENCY = "EURO";
	public static final String ACCOUNT_FOUND = "ACCOUNT FOUND";
	public static final String FIND_BY_PAN_CODE = "SELECT * FROM bank_anagrafic_client b where b.pan_code = ?";
	public static final String FIND_BY_NAME = "SELECT * FROM bank_anagrafic_client b where b.name_user = ?";
	public static final String FIND_BY_EMAIL = "SELECT * FROM bank_anagrafic_client b where b.email = ?";
	public static final String FIND_BY_CLIENT_ID = "SELECT * FROM bank_account_client c where c.client_bank_id = ?";
	public static final String FIND_TRANSACTION_BY_BANK_ACOOUNT_ID = "SELECT * FROM transaction_client t where t.bank_account_id = ?";
	public static final String WITHDRAWL = "withdrawl";
	public static final String DEPOSIT = "deposit";
	public static final String CHECK = "CHECK";
	public static final String CONFIRM = "CONFIRM";
	public static final String ATM_CODE = "5555";
	public static final String ANOMAL = "anomal";
	public static final String REVERSAL = "reversal";
	public static final String BOOTSTRAP_SERVER = "localhost:9092";
	public static final String TOPIC_NAME = "EsercizioFinale";
	public static final String IDENTIFICATIVO_KAFKA_BANK = "ID_1";
	public static final String GROUP_ID = "ANDREI";
	public static final String KAFKA_FILE = "C:\\Users\\alaera\\Desktop\\SpringFile\\KafkaConsumer.txt";
	public static final String TABLE_NAME_BANK_ACCOUNT = "bank_account_client";
	public static final String COLUMN_NAME_BANK_ACCOUNT_CLIENT = "client_bank_id";
	public static final String SAVE_BANK_ACCOUNT_MAPPING = "/save/{panCode}";
	public static final String DELETE_BANK_ACCOUNT_MAPPING = "/delete/{iban}";
	public static final String GET_ALL_BANK_ACCOUNT_MAPPING = "/getAll";
	public static final String GET_IBAN_BANK_ACCOUNT_MAPPING = "/getByIban/{iban}";
	public static final String UPDATE_BANK_ACCOUNT_MAPPING = "/update/{iban}";
	public static final String SAVE_CLIENT_BANK_MAPPING = "/save";
	public static final String GET_ALL_CLIENT_BANK_MAPPING = "/getAll";
	public static final String FIND_BY_EMAIL_CLIENT_BANK_MAPPING = "/findByEmail/{email}";
	public static final String DELETE_CLIENT_BANK_MAPPING = "/delete/{panCode}";
	public static final String UPDATE_CLIENT_BANK_MAPPING = "/update/{panCode}";
	public static final String BALANCE_OPERATION_MAPPING = "/balanceSingle/{iban}";
	public static final String BALANCE_ALL_OPERATION_MAPPING = "/balanceAll/{panCode}";
	public static final String TRANSACTION_CHECK_OPERATION_MAPPING = "/transaction";
	public static final String TRANSACTION_CONFIRM_OPERATION_MAPPING = "/transaction/confirmed";
	public static final String TRANSACTION_DELETE_TRANSACTION_MAPPING = "/delete/{id}";
	public static final String TRANSACTION_FIND_BY_IBAN_TRANSACTION_MAPPING = "/findByIban/{iban}";
	public static final int EXPIRATION_TIME = 10;
	public static final String ERROR_CLIENT_BANK_ACCOUNT_SAVE = "ERROR IN SAVE METHOD FOR BANK ACCOUNT - PAN CODD NOT PRESENT IN THE SYSTEM: ";
	public static final String ERROR_ADMIN_SAVE = "ERROR IN SAVE METHOD FOR ADMIN: ";
	public static final String ERROR_CLIENT_GENERATE_BANK_ACCOUNT = "ERROR CREATE A BANK ACCOUNT: ";
	public static final String ERROR_CLIENT_FIND_ALL_ACCOUNT = "ERROR FIND ALL BANK ACCOUNT: ";
	public static final String ERROR_CLIENT_BANK_ACCOUNT_DELETE = "ERROR DELETING ACCOUNT WITH IBAN ";
	public static final String ENTITY_NOT_FOUND = " ENTITY NOT FOUND";
	public static final String VERIFICATION_TOKEN = "/verifyRegistration/{token}";
	public static final String REQUEST_MAPPING_CONTROLLER_VERIFICATION = "/spring/verification";
	public static final String FIND_BY_TOKEN_VERIFICATION = "select * from verification_token vt where vt.token = ?";
	public static final String VERIFICATE = "VERIFICATE";
	public static final String NOT_VERIFICATE = "NOT VERIFICATE";
	public static final String IS_VERIFICATING = "IS VERIFICATING";
	public static final String FIND_BY_STATUS_AND_PAN_CODE = "SELECT * FROM bank_anagrafic_client b where b.status = ? and b.pan_code = ?";
	public static final String FIND_BY_STATUS = "SELECT * FROM bank_anagrafic_client b where b.status = ?";
	public static final String TOKEN_EXPIRED = " IS NOT VERIFICATE, GENERETING A NEW TOKEN ON YOUR EMAIL FOR CONFIRM YOUR ACCOUNT - IF THE NEW TOKEN DON'T SUCCESS, RE-CREATE YOUR ACCOUNT";
	public static final String EMAIL_SENDER = "bankspringexercise@gmail.com";
	public static final String CLIENT = "client";
	public static final String BANK_ACCOUNT = "bankaccount";
	public static final String TRANSACTION = "transaction";
	public static final String REGISTRATION_TOKEN = "registration_token";
	public static final String EXCEL_PATH_SAVE = "C:\\Users\\alaera\\Desktop\\SpringFile\\ExcelToSave\\";
	public static final String DOWNLOAD_EXCEL_FILE = "localhost:8080/spring/admin/excel/download-excel";
	public static final String NAME_OF_EXCEL_FILE = "excelDatabaseReport.xlsx";
	public static final String HEADER_EXCEL_KEY = "Content-Disposition";
	public static final String HEADER_EXCEL_VALUE = "attachment; filename=";
	public static final String EXCEL_FORMAT_INVALID = "EXCEL DIMENSION OR FORMAT INVALID";
	public static final String CONTENT_TYPE_EXCEL = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	public static final String EXCEL_EXTENSION = "xlsx";
	public static final String ADMIN_ROLE = "ROLE_ADMIN";
	public static final String USER_ROLE = "ROLE_USER";
	public static final String ADMIN_CODE_STARTING = "##ADMIN-";
	public static final String SIGN_KEY = "432A462D4A614E645266556A586E3272357538782F413F4428472B4B62506553";
	public static final int EXPIRATION_TIME_JWT_IN_MINUTE = 5;
}
